substitutions:
  _CACHE_IMAGE: 'gcr.io/${PROJECT_ID}/open-webui:cache'

steps:
  # Pull cache image if it exists
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull ${_CACHE_IMAGE} || echo "No cache image found"'

  # Build with cache
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--cache-from=${_CACHE_IMAGE}'
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'
      - '--build-arg=BUILD_HASH=production-${BUILD_ID}'
      - '-f'
      - 'deployment/Dockerfile.production'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/open-webui:latest'
      - '-t'
      - '${_CACHE_IMAGE}'
      - '.'

images:
  - 'gcr.io/${PROJECT_ID}/open-webui:latest'
  - 'gcr.io/${PROJECT_ID}/open-webui:cache'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  env:
    - 'DOCKER_BUILDKIT=1'

timeout: '1800s'