apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: open-webui
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/timeout: "3600s"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 3600
      containers:
      - name: open-webui
        image: gcr.io/popfly-open-webui/open-webui:latest
        ports:
        - containerPort: 8080
        env:
        # Basic Configuration
        - name: ENV
          value: "prod"
        - name: WEBUI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: webui-secret-key
              key: latest
        
        # OAuth Configuration
        - name: ENABLE_OAUTH_SIGNUP
          value: "True"
        - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
          value: "True"
        
        # Google OAuth Configuration
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-client-id
              key: latest
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client-secret
              key: latest
        - name: GOOGLE_OAUTH_SCOPE
          value: "openid email profile https://www.googleapis.com/auth/admin.directory.group.member.readonly"
        - name: OAUTH_ALLOWED_DOMAINS
          value: "popfly.com"
        
        # Group & Role Management
        - name: ENABLE_OAUTH_GROUP_MANAGEMENT
          value: "True"
        - name: ENABLE_OAUTH_ROLE_MANAGEMENT
          value: "True"
        - name: ENABLE_OAUTH_GROUP_CREATION
          value: "True"
        - name: OAUTH_GROUPS_CLAIM
          value: "groups"
        - name: OAUTH_ROLES_CLAIM
          value: "groups"
        - name: OAUTH_ADMIN_ROLES
          value: "admin,openwebui-admins"
        - name: OAUTH_ALLOWED_ROLES
          value: "user,admin,openwebui-users,openwebui-admins"
        - name: OAUTH_EMAIL_CLAIM
          value: "email"
        - name: OAUTH_PICTURE_CLAIM
          value: "picture"
        - name: OAUTH_USERNAME_CLAIM
          value: "name"
        - name: OAUTH_UPDATE_PICTURE_ON_LOGIN
          value: "True"
        
        # User Permissions
        - name: USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS
          value: "True"
        - name: USER_PERMISSIONS_WORKSPACE_TOOLS_ACCESS
          value: "True"
        - name: USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS
          value: "True"
        - name: USER_PERMISSIONS_WORKSPACE_PROMPTS_ACCESS
          value: "True"
        
        # Database Configuration - Use SQLite in writable directory
        - name: DATABASE_URL
          value: "sqlite:////app/backend/data/webui.db"
        
        # Security & Performance
        - name: SCARF_NO_ANALYTICS
          value: "true"
        - name: DO_NOT_TRACK
          value: "true"
        - name: WEBUI_AUTH
          value: "True"
        
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        
        # Mount volumes for persistent data
        volumeMounts:
        - name: data-volume
          mountPath: /app/backend/data
      
      volumes:
      - name: data-volume
        emptyDir:
          sizeLimit: "2Gi"
  
  traffic:
  - percent: 100
    latestRevision: true